// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import dotenv from "dotenv";
import { defineConfig } from "prisma/config";

dotenv.config({ path: new URL(".env", import.meta.url) });

// Keep DIRECT_URL optional locally/tests: if not set, fall back to DATABASE_URL.
// In production on Neon, you can still set DIRECT_URL to the non-pooled connection.
if (!process.env["DIRECT_URL"] && process.env["DATABASE_URL"]) {
  process.env["DIRECT_URL"] = process.env["DATABASE_URL"];
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
