-- AlterTable
ALTER TABLE "WorkoutSet" ALTER COLUMN "reps" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "TemplateSet" ALTER COLUMN "reps" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "BlockWorkoutSet" ALTER COLUMN "reps" SET DATA TYPE DOUBLE PRECISION;
